name = "logicsekai"
pages_build_output_dir = "./dist"
compatibility_date = "2024-11-09"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "logic_sekai_db"
database_name = "logic-sekai-db"
database_id = "8e584977-b7e9-4f7d-aa4c-a30fab656636"
migrations_dir = "./app/lib/db/migrations"

[vars]
BETTER_AUTH_URL = "https://logicsekai.com"
NODE_ENV = "production"
